{% set version = "1.3.0" %}

package:
  name: python-cdo
  version: {{ version }}

source:
  fn: cdo-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/cdo/cdo-{{ version }}.tar.gz
  sha256: 69368cdf07adf2e138ad799f947375ccdde7b19f62a162afa585b246a2ebc87e

build:
  number: 0
  skip: True  # [win]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - cdo

test:
  imports:
    - cdo

about:
  home: https://code.zmaw.de/projects/cdo/wiki/Cdo%7Brbpy%7D
  license: GPL-2.0
  summary: 'Use CDO in the context of Python as if it would be a native library.'

extra:
  recipe-maintainers:
    - ocefpaf
