travis:
  secure:
    BINSTAR_TOKEN: VETUeExVY/ONOA+AtbXX49r2bCnfc4+vbIV09A3T0WlDZVX1xtqkhiqoWoit7UaTuGRofRL0XU/txVtZO/OasALlVTtSdykI2SHSuRC3rUFZZQ2fOqVFyH/4pObFPstIqZdoAP2OnFfbb1W2L57ADqeZqBy98KArCi54/Ws8uHwjj/GKOAQXaYYzceY0UKa0nurF2FY2cIHMDr38K4xzepmHA8X3B6bXmbxoZS2/JDs5rTv8ArGeTtOZZXjRNiCPvcSBs/pr2LLPPMPsnWKw8Lq9u1m24zXvOsoaBFeTvwtaBXRZsDF9MDGXxWJ96xKki/uXI1PIJTSxtpW2SWKIg3zVU5Gx1xJkiqTbUDHSGZmX+C/DnPdaLEtfD+O2sAS/cLHHn3bl2+qmYv189cBAHcDC2FnmBe5js9vDIcOJdd94iU3TaPdmXQdKsCzWN3S4hlBPQrL3Yk3UPSF/+tqS1bTzrHd4lL/EQ6YleIlSR0Bz/VaIDOOKpjrlH8mTzJ06x5UdZHJqwtnbp7fkrLQ21dpzjT7o4B+vJZ3qJm8aWe2lnMgbdIfNcYY5gNv7kbqh86cr8aaZRppcwXGOgf2wlcg9R4pmxYGBNim37ltuV6z5VJz8pFMA+z1mLRYfCuJVSjy8NS9KeyKOoW/bEY6OnrNyFi5Q+w5xM5XTfFlyapM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
